# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeStarter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeStarter

  pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]

  target 'ReactNativeStarterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
